app/models/product.py
from app.models.factory.validator import Validator
from app.models.factory.database import Database


class Product(object):
    def __init__(self):
        self.validator = Validator()
        self.db = Database()

        self.collection_name = 'product'
        self.fields = {
            "name": "string",
            "description": "string",
            "place": "string",
            "price": "float",
            "shopPrice": "float",
            "currentStock": "int",
            "maxStock": "int",
            "colors": ["string"],
            "_owner": "objectid"
        }

        self.create_required_fields = ["name", "description", "place", "price", "_owner", "currentStock", "maxStock"]

        # Fields optional for CREATE
        self.create_optional_fields = ["colors", "shopPrice"]

        # Fields required for UPDATE
        self.update_required_fields = []

        # Fields optional for UPDATE
        self.update_optional_fields = []

    def create(self, product):
        # Validator will throw error if invalid
        self.validator.validate(product, self.fields, self.create_required_fields, self.create_optional_fields)
        res = self.db.insert(product, self.collection_name)
        return res

    def find(self, product, projection=None):  # find all
        return self.db.find(product, self.collection_name, projection)

    def find_by_id(self, id):
        return self.db.find_by_id(id, self.collection_name)

    def update(self, id, product):
        self.validator.validate(product, self.fields, self.update_required_fields, self.update_optional_fields)
        return self.db.update(id, product, self.collection_name)

    def delete(self, id):
        return self.db.delete(id, self.collection_name)

app/controllers/auth.py
import functools

from flask import Blueprint, jsonify, request, render_template, g, url_for, redirect, session, flash
from bson import ObjectId

from app.models.role import Role
from app.models.user import User
from app.forms import LoginForm, RegisterForm


blueprint = Blueprint('auth', __name__, url_prefix='/auth')


role = Role()
user = User()


@blueprint.route('/register/role', methods=['POST'])
def insert():

    name = request.json.get("name", None)

    error = None

    if not name:
        error = 'Name is required'

    if error is None:
        result = role.find({"name": name},{"name":1})

        if not result:
            id = role.create({"name": name})
            return jsonify(
                msg="Role created!",
                id=id
            )
        else:
            error = "Role already exists"

    msg = {
        "msg": error
    }
    return msg, 409


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if g.user is None:
        if request.method == 'POST' and form.validate():
            username = form.username.data
            password = form.password.data
            try:
                user_found = user.check_credentials({"username": username, "password": password})

                session.clear()
                session['user_id'] = str(user_found['_id'])

                return redirect(url_for('home.home'))
            except Exception as e:
                flash(str(e), 'danger')
        return render_template('login.html', form=form)
    else:
        return redirect(url_for('home.home'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if g.user is None:
        if request.method == 'POST' and form.validate():
            username = form.username.data
            password = form.password.data
            email = form.email.data
            role = form.roles_input.data

            found_user = user.find({"username": username})

            if not found_user:
                try:
                    user_fields = {
                        "username": username,
                        "password": password,
                        "email": email,
                        "_role": ObjectId(role)
                    }
                    id = user.create(user_fields)

                    session.clear()
                    session['user_id'] = str(id.inserted_id)

                    return redirect(url_for('home.home'))
                except Exception as e:
                    flash(str(e), 'danger')

            else:
                flash('User already exists', 'danger')
        return render_template('register.html', form=form)
    else:
        return redirect(url_for('home.home'))


@blueprint.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.home'))


@blueprint.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        user_found = user.find_by_id(user_id)
        role_found = role.find_by_id(user_found["_role"])

        user_found["_role"] = role_found

        g.user = user_found


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)
    return wrapped_view

app/controllers/home.py
from flask import render_template, Blueprint
from app.controllers.auth import login_required


blueprint = Blueprint('home', __name__)


@blueprint.route('/')
@login_required
def home():
    return render_template('home.html')

app/controllers/products.py
from flask import render_template, Blueprint, request, flash, redirect, url_for, g
from app.controllers.auth import login_required
from bson import ObjectId


blueprint = Blueprint('products', __name__, url_prefix='/products')

from app.models.product import Product
from app.forms import AddProductForm


@blueprint.route('/list')
@login_required
def list_products():
    product = Product()
    products_list = product.find(None)

    return render_template('products.html', products=products_list)


@blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_product():
    product = Product()
    form = AddProductForm(request.form)
    if request.method == 'POST' and form.validate():
        name = form.name.data
        description = form.description.data
        place = form.place.data
        price = form.price.data
        max_stock = form.max_stock.data
        colors = form.colors.data

        try:
            product_fields = {
                "name": name,
                "description": description,
                "place": place,
                "price": price,
                "shopPrice": round(price + (price * 0.2), 2),
                "currentStock": 0,
                "maxStock": set_stock(max_stock),
                "colors": colors,
                "_owner": ObjectId(g.user["_id"])
            }

            product.create(product_fields)

            return redirect(url_for('products.list_products'))
        except Exception as e:
            flash(str(e), 'danger')
    return render_template('add_product.html', form=form)


@blueprint.route('/<int:id>/delete', methods=['POST'])
@login_required
def delete_product(id):
    return True



def set_stock(size):
    stock = 100
    if size == "small":
        stock = 320
    elif size == "large":
        stock = 50
    return stock

app/templates/add_product.html
{% from "includes/_formhelpers.html" import render_field %}
{% extends "layout.html" %}

{% block body %}
<main class="my-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Añadir Producto</div>
                        <div class="card-body">
                            <form name="my-form" action="{{url_for('products.add_product')}}" method="post">
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Nombre del producto</label>
                                        <div class="col-md-6">
                                            {{render_field(form.name, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Descripcion</label>
                                        <div class="col-md-6">
                                            {{render_field(form.description, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Lugar de almacenaje</label>
                                        <div class="col-md-6">
                                            {{render_field(form.place, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Precio</label>
                                        <div class="col-md-6">
                                            {{render_field(form.price, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Tamaño del producto</label>
                                        <div class="col-md-6">
                                            {{render_field(form.max_stock, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Colores</label>
                                        <div class="col-md-6">
                                            {{render_field(form.colors, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                        Insertar
                                        </button>
                                    </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}

{% block body %}
    <div class="jumbotron text-center">
        <h1>Hola, Mundo!</h1>
        <p class="lead">Inicio del proyecto para Tokio</p>
    </div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ProyectoPython</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/general.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">
</head>
<body>
    {% include "includes/_navbar.html" %}
    <div class="container">
        {% include 'includes/_messages.html' %}
        {% block body %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/login.html
{% from "includes/_formhelpers.html" import render_field %}
{% extends "layout.html" %}

{% block body %}
    <div class="wrapper fadeInDown">
      <div id="formContent">
        <!-- Tabs Titles -->

        <!-- Icon -->
        <div class="fadeIn first">
          <h1>ProyectoPython</h1>
        </div>

        <!-- Login Form -->
        <form action="{{url_for('auth.login')}}" method="post">
          <div class="form-group">
            {{render_field(form.username, class_="fadeIn second")}}
          </div>
          <div class="form-group">
            {{render_field(form.password, class_="fadeIn third")}}
          </div>
          <input type="submit" class="fadeIn fourth" value="Log In">
        </form>

        <!-- Remind Passowrd -->
        <div id="formFooter">
          <a class="underlineHover" href="{{url_for('auth.register')}}">Register</a>
        </div>

      </div>
    </div>
{% endblock %}

app/templates/products.html
{% extends "layout.html" %}

{% block body %}
<div class="prod-table">
    <div class="row d-flex justify-content-end">
        {% if g.user['_role']['name'] == 'proveedor' or g.user['_role']['name'] == 'admin' %}
           <a href="{{url_for('products.add_product')}}" class="btn btn-success active" role="button" aria-pressed="true">Nuevo Producto</a>
        {% endif %}
    </div>
    <div class="row">
      <table class="table table-striped">
          <caption>Productos disponibles</caption>
          <thead>
              <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Lugar</th>
                    <th scope="col">Unidades</th>
                    <th scope="col">Unidades máximas</th>
                    <th scope="col">Precio Proveedor</th>
                    <th scope="col">Precio en tienda</th>
                    <th scope="col">Acciones</th>
              </tr>
          </thead>
          <tbody>
            {% for product in products %}
                <tr id={{product['_id']}}>
                    <th scope="row">{{ product['name'] }}</th>
                    <td>{{ product['place'] }}</td>
                    <td>{{ product['currentStock'] }}</td>
                    <td>{{ product['maxStock'] }}</td>
                    <td>{{ product['price'] }}</td>
                    <td>{{ product['shopPrice'] }}</td>
                    <td>
                        {% if g.user['_id'] == product['_owner'] or g.user['_role']['name'] == 'admin' %}
                            <a class="action">Editar</a>
                            <a class="action">Borrar</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% from "includes/_formhelpers.html" import render_field %}
{% extends 'layout.html' %}

{% block body %}

<main class="my-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Register</div>
                        <div class="card-body">
                            <form name="my-form" action="{{url_for('auth.register')}}" method="post">
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Username</label>
                                        <div class="col-md-6">
                                            {{render_field(form.username, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Email</label>
                                        <div class="col-md-6">
                                            {{render_field(form.email, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Rol</label>
                                        <div class="col-md-6">
                                            {{render_field(form.roles_input, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Password</label>
                                        <div class="col-md-6">
                                            {{render_field(form.password, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-md-4 col-form-label text-md-right">Confirm Password</label>
                                        <div class="col-md-6">
                                            {{render_field(form.confirm, class_="form-control")}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                        Register
                                        </button>
                                    </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}